### ISSUE TITLE
Requirements

### ISSUE THREAD

**Issue by Mazoise** [nesvoboda/socrates#10]
Hi, I had a small issue installing requirements.
To install psutil you need a few more packages, at least for python 3.7 (I don't know for other versions)
```
sudo apt-get install python3.7-dev
```
solved the problem for me.

Thanks for your tester, it's very useful !

**Comment by cacharle** [comment]
https://pypi.org/project/psutil/

`Supported Python versions are 2.6, 2.7, 3.4+ and PyPy.`

But you need at least Python3.6 because this test uses format strings.

**Comment by arseniycodes** [comment]
Hey @Mazoise, thanks for the tip, I'll add it to the readme. 

And thanks to @cacharle for the tip on Python version, I'll add that too!
