### ISSUE TITLE
Add progress indicator during performance tests

### ISSUE THREAD

**Issue by cacharle** [nesvoboda/socrates#5]
Having to wait 40 seconds without any feedback is frustrating. A timer with the current number of seconds or a progress bar would make the experience better.

**Comment by arseniycodes** [comment]
Good idea! I've used tqdm for that in the past, it seems to have low performance overhead. I'll try to work on it once I have a free moment. But feel free to grab this issue for yourself if you have some time!

**Comment by arseniycodes** [comment]
Added in f62d319 (pull request #6 by @cacharle). Hooray!
